export const ADD_BOARD = 'ADD_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const CHOOSE_BOARD = 'CHOOSE_BOARD';
export const CHANGE_TASK = 'CHANGE_TASK';
export const ADD_TASK_TO_DAY = 'ADD_TASK_TO_DAY';
export const ADD_TASK_TO_STAGE = 'ADD_TASK_TO_STAGE';
export const ADD_TASK_TO_COMPLETED = 'ADD_TASK_TO_COMPLETED';
export const ADD_TASK_TO_UNFULFILLED = 'ADD_TASK_TO_UNFULFILLED';
