const CHANGE_TASK = 'CHANGE_TASK';
const ADD_TASK_TO_DAY = 'ADD_TASK_TO_DAY';
const ADD_TASK_TO_STAGE = 'ADD_TASK_TO_STAGE';
const ADD_TASK_TO_COMPLETED = 'ADD_TASK_TO_COMPLETED';
const ADD_TASK_TO_UNFULFILLED = 'ADD_TASK_TO_UNFULFILLED';
const UPDATE_TASK_ORDER_IN_COLUMN = 'UPDATE_TASK_ORDER_IN_COLUMN';

export default {
  CHANGE_TASK,
  ADD_TASK_TO_DAY,
  ADD_TASK_TO_STAGE,
  ADD_TASK_TO_COMPLETED,
  ADD_TASK_TO_UNFULFILLED,
  UPDATE_TASK_ORDER_IN_COLUMN,
};
